In [1]:
# prompt: 1. What is a Python library? Why do we use Python libraries?

# What is a Python Library?
# A Python library is a collection of pre-written code that you can import into your Python programs
# to reuse functions, classes, and variables without having to write them from scratch.
# Libraries are typically used to simplify complex tasks, provide reusable functionality, and accelerate development.

# Python libraries can range from general-purpose modules (like math and datetime) to specialized
# libraries designed for tasks such as data analysis (like NumPy and pandas), web development (like Django and Flask),
# or machine learning (like TensorFlow and scikit-learn).


# Why Do We Use Python Libraries?
# Reusability: Libraries provide reusable code that you can leverage across different projects, saving time and effort.
# Simplification: Libraries abstract complex tasks into simpler functions, making it easier to perform tasks without understanding all underlying details.
# Efficiency: Libraries often come with optimized code that performs tasks more efficiently than custom implementations.
# Community Support: Many libraries are maintained by a community of developers, ensuring regular updates, bug fixes, and new features.
# Focus on Core Logic: By using libraries, you can focus more on solving the specific problem at hand rather than implementing standard functionality.





import numpy as np

# Create an array
arr = np.array([1, 2, 3, 4])
print(arr)  # Output: [1 2 3 4]

# Calculate the mean of the array
mean = np.mean(arr)
print(mean)  # Output: 2.5


[1 2 3 4]
2.5


In [2]:
# Question: 2. What is the difference between Numpy array and List?


# Differences Between NumPy Array and Python List:

# Data Type Consistency:
# NumPy Array: All elements must be of the same type.
# Python List: Can hold elements of different types.

# Performance:
# NumPy Array: Faster and more memory-efficient due to contiguous memory allocation.
# Python List: Slower and less memory-efficient.

# Functionality:
# NumPy Array: Supports advanced mathematical operations directly.
# Python List: Requires loops or comprehensions for similar tasks.

# Dimensionality:
# NumPy Array: Easily handles multi-dimensional arrays.
# Python List: Can nest lists but is less efficient for multi-dimensional data.

# Memory Consumption:
# NumPy Array: Uses less memory.
# Python List: Consumes more memory due to overhead and diverse types.




#Example
# List
my_list = [1, 2, 3, 'apple', True]
print(my_list)

# Numpy array
import numpy as np
my_array = np.array([1, 2, 3, 4, 5])
print(my_array)


[1, 2, 3, 'apple', True]
[1 2 3 4 5]


In [3]:
# Question: 3. Find the shape, size and dimension of the following array?  [[1, 2, 3, 4]  [5, 6, 7, 8],  [9, 10, 11, 12]]

import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print("Shape:", arr.shape)
print("Size:", arr.size)
print("Dimension:", arr.ndim)


Shape: (3, 4)
Size: 12
Dimension: 2


In [5]:
# Question: 4. Write python code to access the first row of the following array?  [[1, 2, 3, 4]  [5, 6, 7, 8],  [9, 10, 11, 12]]

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(arr[0])


[1 2 3 4]


In [6]:
# Question: 5. How do you access the element at the third row and fourth column from the given numpy array?  [[1, 2, 3, 4]  [5, 6, 7, 8],  [9, 10, 11, 12]]

print(arr[2,3])


12


In [7]:
# Question: 6. Write code to extract all odd-indexed elements from the given numpy array?  [[1, 2, 3, 4]  [5, 6, 7, 8],  [9, 10, 11, 12]]

print(arr[:, 1::2])


[[ 2  4]
 [ 6  8]
 [10 12]]


In [9]:
# Question: 7. How can you generate a random 3x3 matrix with values between 0 and 1?

random_matrix = np.random.rand(3, 3)
print(random_matrix)


[[0.59266671 0.33949863 0.37875325]
 [0.03987914 0.19675494 0.78189966]
 [0.25671121 0.98231109 0.09987611]]


In [10]:
# Question: 8. Describe the difference between np.random.rand and np.random.randn?

# np.random.rand generates random numbers from a uniform distribution between 0 and 1.
uniform_random = np.random.rand(3, 3)
print("Uniform Random Matrix:")
print(uniform_random)

# np.random.randn generates random numbers from a standard normal distribution (mean 0, variance 1).
normal_random = np.random.randn(3, 3)
print("\nNormal Random Matrix:")
print(normal_random)


Uniform Random Matrix:
[[0.03906306 0.97591156 0.25079874]
 [0.32044803 0.64633591 0.72724502]
 [0.15375202 0.043061   0.5408723 ]]

Normal Random Matrix:
[[ 0.25888822 -0.78384322  0.5513841 ]
 [-0.73094399 -0.97715387  0.03510352]
 [-0.5643917   0.81629425  1.85814431]]


In [14]:
# Question: 9. Write code to increase the dimension of the following array?
#  [[1, 2, 3, 4]  [5, 6,7, 8],  [9, 10, 11, 12]]

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
new_arr = arr.reshape(2, 2, 3)
print(new_arr)


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [15]:
# Question: 10. How to transpose the following array in NumPy?  [[1, 2, 3, 4]  [5, 6, 7, 8],  [9, 10, 11, 12]]

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
transposed_arr = arr.transpose()
print(transposed_arr)


[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [16]:
# Question: 11. Consider the following matrix:
# Matrix A: [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
# Matrix B: [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
# Perform the following operation using Python
# 1. Index wise multiplication
# 2. Matrix multiplication
# 3. Add both the matrix
# 4. Subtract matrix B from A
# 5. Divide Matrix B by A

A = np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]])
B = np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]])

# Index wise multiplication
index_wise_mult = A * B
print("Index Wise Multiplication:\n", index_wise_mult)

# Matrix multiplication
matrix_mult = np.dot(A, B.T) # Note: B is transposed to make dimensions compatible for matrix multiplication
print("\nMatrix Multiplication:\n", matrix_mult)

# Add both matrices
addition = A + B
print("\nAddition:\n", addition)

# Subtract matrix B from A
subtraction = A - B
print("\nSubtraction:\n", subtraction)

# Divide Matrix B by A (element-wise)
division = B / A
print("\nDivision:\n", division)


Index Wise Multiplication:
 [[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]

Matrix Multiplication:
 [[ 30  70 110]
 [ 70 174 278]
 [110 278 446]]

Addition:
 [[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]

Subtraction:
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

Division:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [22]:
# Question: 12. Which function in Numpy can be used to swap the byte order of an array? give an example

# The function in NumPy used to swap the byte order of an array is `np.byteswap`.

# Example:
arr = np.array([1, 256, 65536], dtype=np.int32)
print("Original array:", arr)
print("Byte order:", arr.dtype.byteorder)

swapped_arr = arr.byteswap()
print("\nSwapped array:", swapped_arr)
print("Byte order after swapping:", swapped_arr.dtype.byteorder)


Original array: [    1   256 65536]
Byte order: =

Swapped array: [16777216    65536      256]
Byte order after swapping: =


In [24]:
# Question: 13. What is the significance of the np.linalg.inv function?

import numpy as np

# Define a square matrix
A = np.array([[1, 2], [3, 4]])

# Calculate the inverse of the matrix
A_inv = np.linalg.inv(A)

print("Matrix A:\n", A)
print("\nInverse of Matrix A:\n", A_inv)

# Verify the property of inverse matrix
identity_matrix = np.dot(A, A_inv)
print("\nProduct of A and its inverse:\n", identity_matrix)


Matrix A:
 [[1 2]
 [3 4]]

Inverse of Matrix A:
 [[-2.   1. ]
 [ 1.5 -0.5]]

Product of A and its inverse:
 [[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


In [26]:
# Question: 14. What does the np.reshape function do, and how is it used?

# Significance of np.linalg.inv:
# Solving Linear Equations: The inverse of a matrix is often used to solve systems of linear equations. If
# A×X=B, then 𝑋=𝐴^-1×𝐵

# Linear Transformations: Inverse matrices are used in various applications involving linear transformations,
# such as computer graphics, data analysis, and engineering.

# Matrix Operations: Certain matrix operations, like finding solutions to certain types of equations,
# require the use of the inverse matrix.



# Example: Reshaping a 1D array to a 2D array
arr = np.array([1, 2, 3, 4, 5, 6])
new_arr = arr.reshape(2, 3)
print(new_arr)


[[1 2 3]
 [4 5 6]]


In [25]:
# Question: 15. What is broadcasting in Numpy?

# Answer:
# Broadcasting in NumPy is a powerful mechanism that allows operations to be performed
# on arrays of different shapes in a way that would not normally be possible.
# It automatically expands the smaller array along the missing dimensions so that the shapes
# are compatible for element-wise operations, without making unnecessary copies of data.

# How Broadcasting Works?
# Broadcasting works according to these rules:

# Matching Dimensions: When performing operations on two arrays, NumPy compares their
# shapes element-wise, starting from the trailing (right-most) dimensions.

# Dimension Compatibility:

# If the dimensions are equal, they are compatible.
# If one of the dimensions is 1, it can be stretched to match the other dimension.
# If the dimensions are not equal and neither is 1, an error is raised.
# Automatic Expansion: The array with a dimension of 1 is virtually repeated to match
# the size of the other array along that dimension, allowing the operation to proceed as if both arrays were of the same shape.





import numpy as np

a = np.array([1, 2, 3])  # Shape (3,)
b = np.array([[4], [5], [6]])  # Shape (3, 1)

result = a + b
print(result)  # Output: [[5 6 7] [6 7 8] [7 8 9]]


# Advantages of Broadcasting:
# Memory Efficiency: Broadcasting avoids the need to create large, repeated arrays, leading to more efficient memory usage.
# Code Simplicity: It simplifies code by eliminating the need for explicit loops to perform operations on arrays of different shapes.

[[5 6 7]
 [6 7 8]
 [7 8 9]]
